### ISSUE TITLE
Convenient keys

### ISSUE THREAD

**Issue by qrpike** [bassochette/polygon.io#1]
Hey, great library so far! 

The only thing I can see would be making the keys of objects more human friendly. There isn't an exact mapping we are looking for, just whatever the actual key means -> camel cased name. 

eg:

```javascript
let trade = {
    ticker: rawTrade.T,
    timestamp: rawTrade.t,
    size: rawTrade.s,
    price: rawTrade.p,
    // etc etc
}
```

I think this will make the library much easier for users to consume. 

Thanks,

**Comment by bassochette** [comment]
I'm concerned that it will make the node client inconsistent with your current api documentation.

Will you host the node client documentation?

**Comment by bassochette** [comment]
Done and publish on version 0.7.0
