### ISSUE TITLE
Multi instance initialization

### ISSUE THREAD

**Issue by qrpike** [bassochette/polygon.io#2]
One more thing I noticed is it seems the library works on a global scope, meaning 1 init function handles the library and any methods in the library will be under that. Can we make the library be more class based so that users may use multiple instances in the same code. 

```javascript

import { websockets } from 'polygon.io'

// Websockets Client:
const ws1 = websockets.Init({ apiKey: 'XXX' })
const stocksWs = ws1.getStocksWebsockets()

// Crypto Client:
const ws2 = websockets.Init({ apiKey: 'YYY' })
const cryptoWs = ws2.getCryptoWebsockets()

```

**Comment by bassochette** [comment]
All right, it's merged and published in version 1.0.0.

the whole polygon can be multi-instanced, the rest client and the websocket client can also be.
And submodules can be multi instanced.
